# Generated by Django 3.0.7 on 2020-06-13 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField()),
                ('state', models.CharField(choices=[('INACTIVE', 'Inactive'), ('ACTIVE', 'Active'), ('COMMITTED', 'Committed')], default='INACTIVE', max_length=10)),
                ('title', models.CharField(max_length=256)),
                ('terms', models.CharField(max_length=65536)),
                ('end_date', models.DateField()),
                ('number', models.IntegerField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField()),
                ('state', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'ClosedI')], default='OPEN', max_length=10)),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=65536)),
                ('number', models.IntegerField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='IssueComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField()),
                ('body', models.CharField(max_length=65536)),
                ('issue', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.Issue')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='IssueStateHistoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('state', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'ClosedI')], editable=False, max_length=10)),
                ('issue', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='state_history', to='api.Issue')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IssueDescriptionHistoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('state', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'ClosedI')], editable=False, max_length=10)),
                ('issue', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='description_history', to='api.Issue')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IssueCommentHistoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('body', models.CharField(editable=False, max_length=65536)),
                ('comment', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.IssueComment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='api.Lab'),
        ),
        migrations.CreateModel(
            name='ExperimentTermsHistoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('body', models.CharField(editable=False, max_length=65536)),
                ('experiment', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='terms_history', to='api.Experiment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExperimentEndDateHistoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('end_date', models.DateField(editable=False)),
                ('experiment', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='end_date_history', to='api.Experiment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='experiment',
            name='issues',
            field=models.ManyToManyField(related_name='experiments', to='api.Issue'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='api.Lab'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(fields=('number', 'lab'), name='issue_unique_number_in_lab'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.CheckConstraint(check=models.Q(number__gte=1), name='issue_number_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='experiment',
            constraint=models.UniqueConstraint(fields=('number', 'lab'), name='experiment_unique_number_in_lab'),
        ),
        migrations.AddConstraint(
            model_name='experiment',
            constraint=models.CheckConstraint(check=models.Q(number__gte=1), name='experiment_number_gte_1'),
        ),
    ]
