# Generated by Django 3.0.7 on 2020-06-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='number',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='state',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='issuedescriptionhistoryitem',
            name='state',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='issuestatehistoryitem',
            name='state',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], editable=False, max_length=10),
        ),
    ]
