# Generated by Django 3.0.7 on 2020-06-22 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200613_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.CharField(default='', max_length=65536),
        ),
        migrations.AlterField(
            model_name='issuecomment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.Issue'),
        ),
        migrations.AlterField(
            model_name='issuecommenthistoryitem',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.IssueComment'),
        ),
        migrations.AlterField(
            model_name='issuestatehistoryitem',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_history', to='api.Issue'),
        ),
    ]
