# Generated by Django 3.0.7 on 2020-06-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_experiment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='number',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
