# Generated by Django 3.0.7 on 2020-06-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200625_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='state',
            field=models.CharField(choices=[('INACTIVE', 'Inactive'), ('ACTIVE', 'Active'), ('COMMITTED', 'Committed')], default='ACTIVE', max_length=10),
        ),
    ]
