# Generated by Django 3.0.7 on 2020-06-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200630_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='experiments',
            field=models.ManyToManyField(related_name='check_ins', to='api.Experiment'),
        ),
    ]
