# Generated by Django 3.0.7 on 2020-07-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200630_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='experiments',
            field=models.ManyToManyField(null=True, related_name='check_ins', to='api.Experiment'),
        ),
    ]
