# Generated by Django 3.0.7 on 2020-07-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200701_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='experiments',
            field=models.ManyToManyField(blank=True, related_name='check_ins', to='api.Experiment'),
        ),
    ]
